--- #YAML:1.0
name:               Tie-Hash-Random
version:            1.02
abstract:           A tied hash that generate random
author:
    - Matias Alejo Garcia ( matiu@cpan.org ) 
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Random:  ~
    Scalar::Util:  ~
    Test::More:    0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
